version: '2'
services:
  postgresql: 
    image: postgres:10.5
    container_name: hack-postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    hostname: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
  superset:
    image: apache/superset
    container_name: superset
    ports:
      - 8088:8088
    volumes: 
      - ./superset.db:/app/superset-home/superset.db
