version: '2'
services:
  server:
    build:
      context: ./server/
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - 8888:8080
  
  postgresql: ## DB for MLFLOW
    image: postgres:10.5
    container_name: hack-postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
    hostname: postgresql
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    
  mlflow:
    build: ./mlflow
    container_name: hack-mlflow
    depends_on:
      - postgresql
    expose: 
      - ${MLFLOW_PORT}
    ports:
      - ${MLFLOW_PORT}:${MLFLOW_PORT}
    environment:
      MLFLOW_PORT: ${MLFLOW_PORT}
      DB_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@hack-postgresql:5432/${POSTGRES_DB}
      VIRTUAL_HOST: ${HOST}
      VIRTUAL_PORT: ${MLFLOW_PORT}
      FTP_URI: ftp://username:${FTP_PASSWORD}@${MLFLOW_IP}:21
    restart: always

  ftpd_server:
    image: bogem/ftp
    container_name: hack-ftp_server
    ports:
      - 820:20
      - 821:21
    volumes:
      - ./artifacts:/home/vsftpd
    environment:
      FTP_USER: username
      FTP_PASS: ${FTP_PASSWORD}
      PASV_ADDRESS: ${MLFLOW_IP}
    restart: always

  superset:
    image: apache/superset
    container_name: superset
    ports:
      - 8088:8088